title: hao-yung weng
email: haoyungw@cs.cmu.edu
description: >-
  hao-yung's personal website
baseurl: ""
url: "https://haoyungweng.me/"
github_username:  haoyungweng

plugins:
  - jekyll-feed
  - jekyll-seo-tag